### ISSUE TITLE
Wordsbatte resizing is not working for smaller screens

### ISSUE THREAD

**Issue by seattleuser** [seattleuser/DTML.Games#9]
The flags are being cut off
![bug1](https://user-images.githubusercontent.com/16449461/37878195-f3dc953e-3019-11e8-8628-b1ffdaa8fef2.JPG)

**Comment by Jabito** [comment]
Pushed fix. Kindly test.

**Comment by Jabito** [comment]
I tried a different scaling approach. More responsive but the quality may diminish on smaller phones. Let me know how it looks.

**Comment by seattleuser** [comment]
Can you fix other bugs and we will test all in once?

**Comment by seattleuser** [comment]
I tested locally a little and the gnome disappeares after first wrong word

![image](https://user-images.githubusercontent.com/16449461/37886454-5d2cc814-3070-11e8-828b-553ed3541721.png)

**Comment by Jabito** [comment]
Okay. I will have them fixed in a bit including the others. Ill update you
soon.

Jabito

**Comment by Jabito** [comment]
I pushed the fix for this. I'm only having trouble with the response of the language API for vi. I'm decoding it as application/json and it is really distorted. I'm trying to look for a work around. In the meantime, I'll finish up family tree.

Let me know if there are issues with the updated game.

**Comment by Jabito** [comment]
Attaching image.
![image](https://user-images.githubusercontent.com/10280963/37896658-da145a76-3116-11e8-8dc0-2e09b5134e8d.png)

**Comment by seattleuser** [comment]
It is not distorted it is encoded in Unicode. Browsers know how to render these. This of that as HTML. So, assume you are getting back not text but HTML and in your code instead of .text() use .html()
